services:
  gnode:
    image: alexgale/gnode:dev
    container_name: gnode
    command: sh -c "npx nodemon index.js --ignore localconfig"
    pid: "host"
    working_dir: /app
    volumes:
      - ./localconfig:/config
      - ./:/app:cached
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile